//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchView
    {
        public System.DateTime DRDate { get; set; }
        public System.DateTime DRTime { get; set; }
        public string EID { get; set; }
        public string Remarks { get; set; }
        public string SBDSB { get; set; }
        public string Status { get; set; }
    }
}
