//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbInventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SbDBEntities : DbContext
    {
        public SbDBEntities()
            : base("name=SbDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RPO> RPOes { get; set; }
        public virtual DbSet<RPOLogin> RPOLogins { get; set; }
        public virtual DbSet<SBDispatch> SBDispatches { get; set; }
        public virtual DbSet<SBDSB> SBDSBs { get; set; }
        public virtual DbSet<SBReceive> SBReceives { get; set; }
    }
}
