//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBDSB
    {
        public SBDSB()
        {
            this.SBDispatches = new HashSet<SBDispatch>();
            this.SBReceives = new HashSet<SBReceive>();
        }
    
        public int Id { get; set; }
        public int RPOId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SBDispatch> SBDispatches { get; set; }
        public virtual ICollection<SBReceive> SBReceives { get; set; }
    }
}
